CREATE TABLE [BookGenrePairs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [BookId] INT NOT NULL FOREIGN KEY REFERENCES Books(Id), 
    [GenreId] INT NOT NULL FOREIGN KEY REFERENCES Genres(Id)
)