CREATE TABLE [BookAuthorPairs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [BookId] INT NOT NULL FOREIGN KEY REFERENCES Books(Id), 
    [AuthorId] INT NOT NULL FOREIGN KEY REFERENCES Authors(Id)
)